version: "3"

services:
  app:
    image: "node:11-alpine"
    build: "./"
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
    ports:
      - "8000:8000"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "./data/db:/data/db"
