version: '3'

services: 
  app:
    image: "node:11-alpine"
    volumes:
      - "./:/app"
    working_dir: "/app"
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
    ports:
      - "8000:8000"
    command: "npm run dev"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "./data/db:/data/db"